spring:
    profiles:
        active: dev
    main:
        allow-bean-definition-overriding: true
    jpa:
        database-platform: "org.hibernate.dialect.PostgreSQLDialect"
        database: POSTGRESQL
        show-sql: false
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
        properties:
            hibernate.jdbc.time_zone: UTC
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.temp.use_jdbc_metadata_defaults: false

    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: HTML

server:
    port: ${LISTEN_PORT:8080}
    servlet:
        session:
            cookie:
                http-only: true